### ISSUE TITLE
failing to deploy it on railway. below is error log 

### ISSUE THREAD

**Issue by JosephGMkonda** [JosephGMkonda/MyWebSite#1]
#10 17.76   Getting requirements to build wheel: started

 

#10 18.01   Getting requirements to build wheel: finished with status 'error'

 

#10 18.02   error: subprocess-exited-with-error

#10 18.02

#10 18.02   × Getting requirements to build wheel did not run successfully.

 

#10 18.02   │ exit code: 1

#10 18.02   ╰─> [24 lines of output]

#10 18.02       Trying pkg-config --exists mysqlclient

#10 18.02       Command 'pkg-config --exists mysqlclient' returned non-zero exit status 1.

#10 18.02       Trying pkg-config --exists mariadb

#10 18.02       Command 'pkg-config --exists mariadb' returned non-zero exit status 1.

#10 18.02       Trying pkg-config --exists libmariadb

#10 18.02       Command 'pkg-config --exists libmariadb' returned non-zero exit status 1.

#10 18.02       Traceback (most recent call last):

#10 18.02         File "/opt/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>

 

#10 18.02           main()

#10 18.02         File "/opt/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main

#10 18.02           json_out['return_val'] = hook(**hook_input['kwargs'])

#10 18.02         File "/opt/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel

#10 18.02           return hook(config_settings)

#10 18.02         File "/tmp/pip-build-env-qx5lsi1s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel

#10 18.02           return self._get_build_requires(config_settings, requirements=['wheel'])

#10 18.02         File "/tmp/pip-build-env-qx5lsi1s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires

#10 18.02           self.run_setup()

#10 18.02         File "/tmp/pip-build-env-qx5lsi1s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup

#10 18.02           exec(code, locals())

#10 18.02         File "<string>", line 155, in <module>

#10 18.02         File "<string>", line 49, in get_config_posix

#10 18.02         File "<string>", line 28, in find_package_name

#10 18.02       Exception: Can not find valid pkg-config name.

#10 18.02       Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually

#10 18.02       [end of output]

#10 18.02

#10 18.02   note: This error originates from a subprocess, and is likely not a problem with pip.

#10 18.03 error: subprocess-exited-with-error

 

#10 18.03

#10 18.03 × Getting requirements to build wheel did not run successfully.

#10 18.03 │ exit code: 1

**Comment by JosephGMkonda** [comment]
help me to deploy it
